import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WithSidebar } from "@/components/ui/with-sidebar";
import SidebarContent from "@/components/ui/sidebar-content";
import CustomHeader from "@/components/ui/custom-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WithSidebar
          sidebarContent={SidebarContent}
          mobileDashboardHeader={CustomHeader}>
          {children}
        </WithSidebar>
      </body>
    </html>
  );
}
